version: '3'
services:
  frontend:
    build: 
      context: ./front-end
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
  backend:
    build: 
      context: ./back-end
      dockerfile: Dockerfile
    ports:
      - '5000:5000'
    depends_on:
      - mongo_db
  mongo_db:
    image: mongo:latest
    volumes:
      - mongo-data:/data/db
    ports:
      - '27017:27017'
volumes:
  mongo-data:
    driver: local
