
name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        directory: ['front-end', 'back-end']
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18.20.5'

    - name: Cache node modules
      uses: actions/cache@v2
      with:
        path: ${{ matrix.directory }}/node_modules
        key: ${{ runner.os }}-node-${{ hashFiles(matrix.directory + '/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Install dependencies
      run: npm install
      working-directory: ${{ matrix.directory }}
    
    - name: Run tests
      run: npm test
      working-directory: ${{ matrix.directory }}
